targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/data/models/**
      source_gen|combining_builder:
        generate_for:
          - lib/data/models/**.dart
